<div class="mainHome">

  <div class="mainHome__leftHome">

    <div class="leftHome__cardHome">
      <?php
      echo '<h2 class="cardHome__welcome">Bem-vindo ' . $_SESSION['name'] . '</h2>';
      ?>
      <a class="cardHome__logout" href="?logout">Fazer logout!</a>
    </div>

  </div>

  <div class="mainHome__rightHome">
    <h2 class="cardHome__welcome">Você foi logado com sucesso!</h2>
    <img src="./../assets/images/home.svg" class="rightHome__img" alt="Homem escrevendo em um papel na tela do computador com objetos de escritório ao fundo, animação">
  </div>

</div>